# Source: cd-indicators/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-indicators
  labels:
    app.kubernetes.io/name: cd-indicators
    app.kubernetes.io/instance: "cd-indicators"
    helm.sh/chart: cd-indicators-0.0.18
    app.kubernetes.io/version: "0.0.18"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'cd-indicators'
  namespace: jx
